language: ruby
rvm:
  - 2.7
sudo: false
cache: bundler
script:
  - bundle exec middleman build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      bundle exec middleman deploy;
    fi